vim.g.mapleader = " " -- leader key
vim.opt.termguicolors = true
vim.o.tabstop = 4 -- A TAB character looks like 4 spaces
vim.o.expandtab = true -- Pressing the TAB key will insert spaces instead of a TAB character
vim.o.softtabstop = 4 -- Number of spaces inserted instead of a TAB character
vim.o.shiftwidth = 4 -- Number of spaces inserted when indenting
vim.o.gdefault = true -- default g behaviour for substitute
vim.o.hlsearch = false -- highlight search
vim.o.termguicolors = true -- gui colors
vim.wo.number = true -- line numbers
vim.wo.relativenumber = true -- relative line numbers
